export const CHECK_ALL_IMPORTS_ADDRESSES = "CHECK_ALL_IMPORTS_ADDRESSES";
export const CHECK_STATIC_IMPORTS_ADDRESSES = "CHECK_STATIC_IMPORTS_ADDRESSES";
export const CHECK_IMPORTS = "CHECK_IMPORTS";
export const CHECK_USAGE = "CHECK_USAGE";
export const CHECK_EXPORTS = "CHECK_EXPORTS";

export const CHECK_DEPENDENCIES_AT_GIVEN_DEPTH =
  "CHECK_DEPENDENCIES_AT_GIVEN_DEPTH";
export const CHECK_DEAD_FILES = "CHECK_DEAD_FILES";
export const CHECK_FILES_CONTRIBUTING_IN_MULTIPLE_CHUNKS =
  "CHECK_FILES_CONTRIBUTING_IN_MULTIPLE_CHUNKS";
export const CHECK_CHUNK_METADATA_USING_GIVEN_FILE =
  "CHECK_CHUNK_METADATA_USING_GIVEN_FILE";
export const DISPLAY_TEXT = "DISPLAY_TEXT";